### ISSUE TITLE
Unable to use this extension in VS Code sources

### ISSUE THREAD

**Issue by bpasero** [danvk/any-xray#15]
👋 nice extension, I tried using it for VS Code development but I see this error when I open any TS file while the extension is running:

```
TypeError: Cannot read properties of undefined (reading 'getProgram')
    at findTheAnys (/Users/bpasero/.vscode-insiders/extensions/danvk.any-xray-0.1.1/out/extension.js:116:37)
    at invokeFunc (/Users/bpasero/.vscode-insiders/extensions/danvk.any-xray-0.1.1/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Users/bpasero/.vscode-insiders/extensions/danvk.any-xray-0.1.1/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/Users/bpasero/.vscode-insiders/extensions/danvk.any-xray-0.1.1/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
```

**Steps:**
* open a file such as `src/vs/base/common/event.ts` from https://github.com/Microsoft/vscode/

**Comment by danvk** [comment]
Fixed by #17 (0.2.0)

Here are a few sneaky `any`s in `event.ts`:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/371d2972-1acc-4472-9039-a212dc8a17cc">
