### ISSUE TITLE
Unable to parse `checker.ts`

### ISSUE THREAD

**Issue by danvk** [danvk/any-xray#19]
The ultimate test for any TypeScript tool! Here's what I see in the extension logs:

```
[Extension Host] parsed /Users/danvk/github/TypeScript/src/compiler/checker.ts in 218 ms
[Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'buildError')
[Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'buildError')
    at Scope.checkBlockScopedCollisions (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:395:27)
    at Scope.registerBinding (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:494:16)
    at Scope.registerDeclaration (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:446:14)
    at Object.BlockScoped (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:259:12)
    at Object.newFn (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/visitors.js:207:17)
    at NodePath._call (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:49:20)
    at NodePath.call (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:35:15)
    at NodePath.visit (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:88:31)
    at TraversalContext.visitQueue (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitMultiple (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:62:17)
    at TraversalContext.visit (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:111:19)
    at traverseNode (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/index.js:53:34)
    at NodePath.traverse (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/index.js:120:24)
    at Scope.crawl (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:654:10)
    at Scope.init (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/scope/index.js:625:12)
    at NodePath.setScope (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:126:53)
    at NodePath.setContext (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:138:12)
    at NodePath.pushContext (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/path/context.js:195:8)
    at TraversalContext.visitQueue (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:82:30)
    at TraversalContext.visitSingle (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:66:19)
    at TraversalContext.visit (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/context.js:113:19)
    at traverseNode (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/@babel/traverse/lib/index.js:53:34)
    at findTheAnys (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/out/extension.js:147:28)
    at invokeFunc (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/Users/danvk/.vscode/extensions/danvk.any-xray-0.2.0/node_modules/lodash.debounce/index.js:195:14)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
```

So this seems like an issue with babel.

218 ms to parse `checker.ts` with `@babel/parser` isn't bad!

**Comment by danvk** [comment]
This is a minimal repro of the offending code:

```ts
import { SymbolLinks } from "./_namespaces/ts.js";
const SymbolLinks = class implements SymbolLinks {
  declare _symbolLinksBrand: any;
};
```

Searching for `checkBlockScopedCollisions` on the babel repo led me to https://github.com/babel/babel/issues/12950, which suggests adding `noScope: true` to the `traverse` call as a workaround. That should do the trick. I didn't realize babel tracked scope like this — that might actually be a way to detect the "evolving any" pattern.
